<a href="https://colab.research.google.com/github/Usermer/deep-learning-universe/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch gymnasium stable-baselines3 numpy matplotlib --quiet

In [1]:
import torch
from torch import nn

In [ ]:
torch.rand(2,2)

tensor([[0.9476, 0.6812],
        [0.6278, 0.0547]])

In [ ]:
x=torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [ ]:
x[0][0]=5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [ ]:
torch.zeros(2,2)


tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.ones(1,2)

tensor([[1., 1.]])

In [ ]:
torch.ones(1,2)+torch.ones(1,2)

tensor([[2., 2.]])

In [ ]:
torch.rand(1)

tensor([0.0741])

In [ ]:
torch.rand(1).item()

0.006076931953430176

A **`LongTensor`** (also known as `torch.int64`) is used to store 64-bit signed integers. It's often used for things like indices, labels, or counting values.

In [ ]:


# Creating a LongTensor
long_tensor = torch.tensor([1, 2, 3, 4], dtype=torch.long)
print(f"Long Tensor: {long_tensor}, Data Type: {long_tensor.dtype}")

Long Tensor: tensor([1, 2, 3, 4]), Data Type: torch.int64


In [ ]:
long_tensor=torch.tensor([[0,0,1],[0,0,0],[1,1,1]])
print(long_tensor.type())
print(long_tensor.dtype)

torch.LongTensor
torch.int64


A **`FloatTensor`** (also known as `torch.float32`) is used to store 32-bit floating-point numbers. This is the default data type for many operations involving real numbers, especially in neural networks where precision is often 32-bit.

In [ ]:

# Creating a FloatTensor
float_tensor = torch.tensor([1.0, 2.5, 3.7], dtype=torch.float)
print(f"Float Tensor: {float_tensor}, Data Type: {float_tensor.dtype}")

# By default, numbers with a decimal point will often be inferred as float
default_float_tensor = torch.tensor([1., 2., 3.])
print(f"Default Float Tensor: {default_float_tensor}, Data Type: {default_float_tensor.dtype}")

Float Tensor: tensor([1.0000, 2.5000, 3.7000]), Data Type: torch.float32
Default Float Tensor: tensor([1., 2., 3.]), Data Type: torch.float32


You can easily convert between these data types using methods like `.long()`, `.float()`, `.double()`, or `.to(dtype)`.

In [ ]:

# Convert FloatTensor to LongTensor
converted_long_tensor = float_tensor.long()
print(f"Converted to Long Tensor: {converted_long_tensor}, Data Type: {converted_long_tensor.dtype}")

# Convert LongTensor to FloatTensor
converted_float_tensor = long_tensor.float()
print(f"Converted to Float Tensor: {converted_float_tensor}, Data Type: {converted_float_tensor.dtype}")

# Using .to(dtype)
converted_to_double = float_tensor.to(torch.double)
print(f"Converted to Double Tensor: {converted_to_double}, Data Type: {converted_to_double.dtype}")

Converted to Long Tensor: tensor([1, 2, 3]), Data Type: torch.int64
Converted to Float Tensor: tensor([[0., 0., 1.],
        [0., 0., 0.],
        [1., 1., 1.]]), Data Type: torch.float32
Converted to Double Tensor: tensor([1.0000, 2.5000, 3.7000], dtype=torch.float64), Data Type: torch.float64


Most functions that operate on a tensor and return a tensor create a new tensor to store the result.However , if you want to save memory,look to see if an *in_place function* is defined, which should be he same name as the original but with an appended under_score(_).

In [ ]:


a = torch.tensor([1, 2, 3], dtype=torch.float)
print(f"Original tensor 'a': {a}")

# Non-in-place operation: creates a new tensor
a.add(4) # or a + 4
print(f"'a' after non-in-place add (unchanged): {a}\n")


Original tensor 'a': tensor([1., 2., 3.])
'a' after non-in-place add (unchanged): tensor([1., 2., 3.])



In [ ]:

# In-place operation: modifies 'a' directly
a.add_(5) # modifies 'a' in-place
print(f"Tensor 'a' after in-place add: {a}")

Tensor 'a' after in-place add: tensor([6., 7., 8.])


In [ ]:
random_tensor=torch.rand(2,2)
random_tensor.log2()
random_tensor

tensor([[6.6614e-01, 8.8418e-01],
        [7.7039e-04, 5.9605e-01]])

In [ ]:
random_tensor.log2_()

tensor([[ -0.5861,  -0.1776],
        [-10.3421,  -0.7465]])

**Reshaping tensors**

Both `view()` and `reshape()` methods are used to change the shape of a tensor in PyTorch. However, there's a subtle but important difference in how they operate, especially concerning memory.

`view()`: This method returns a new tensor with the same data as the original tensor but with a different shape. **The key characteristic of view() is that it requires the original tensor to be contiguous in memory**. If the tensor is contiguous, view() will share the underlying data with the original tensor, making it a very memory-efficient operation. Changes to the viewed tensor will affect the original, and vice-versa.

`reshape()`: This method also returns a tensor with the specified shape. Unlike view(), **reshape() does not require the tensor to be contiguous.** If the tensor is contiguous, reshape() behaves exactly like view() (i.e., it will share the underlying data). However, if the tensor is not contiguous, reshape() will create a new contiguous copy of the data before reshaping it. This means reshape() can sometimes involve a data copy, making it less memory-efficient than view() in those cases. Changes to a reshaped tensor might or might not affect the original, depending on whether a copy was made.

In most common scenarios, you can use reshape() as it handles contiguity automatically.

In [ ]:
flat_tensor=torch.rand(784)
viewed_tensor=flat_tensor.view(1,28,28)
viewed_tensor.shape

torch.Size([1, 28, 28])

In [ ]:
reshaped_tensor=flat_tensor.reshape(1,28,28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

Class nn.module

A **`torch.nn.Module`** is the base class for all neural network modules in PyTorch. It's a fundamental building block for creating neural networks, from simple layers to complex architectures.

Key features of `nn.Module`:
- **Manages parameters**: It automatically tracks all parameters (learnable weights and biases) defined within its subclasses.
- **Provides common functionalities**: Includes methods for moving the module to different devices (`.to()`), saving/loading (`.state_dict()`, `.load_state_dict()`), and managing training/evaluation modes (`.train()`, `.eval()`).
- **Defines the `forward` pass**: Every `nn.Module` subclass must implement the `forward` method, which defines how input data is processed through the network to produce an output.

In [3]:
#on herite de la classe nn.Module
class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    #.Parameter :tenseur special
    #les poids seront automatiquement detectes par .paremetres, sauvegardes par .save()
    #et aussi optimises
    self.weights=nn.Parameter(torch.randn(1,
                                          requires_grad=True,#si resquires_grad=False donc les parametres sont non-entrainables
                                          stype=torch.float))
    self.biais=nn.Parameter(torch.randn(1,
                                          requires_grad=True,
                                          stype=torch.float))


  def forward(self,x:torch.Tensor)->torch.Tensor: #"x" is yhe input
    return self.weights*x+self.biais #linear regression formula

